name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purescript-contrib/setup-purescript@main

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build and test with Spago
        run: |
          npm install
          npx spago test
